// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import FlashController from "controllers/flash_controller"
application.register("flash", FlashController)

import MentionController from "controllers/mention_controller"
application.register("mention", MentionController)
