volumes:
  db-volume:
services:
  db:
    image: postgres:16
    env_file: .env
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - 'db-volume:/var/lib/postgressql/data'
  web-app:
    build: .
    working_dir: /equipment-management-app
    ports:
      - '3000:3000'
    volumes:
      - '.:/equipment-management-app'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: db
    depends_on: 
      - db
    tty: true
    stdin_open: true
    command: tail -f /dev/null
  
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
    shm_size: '2gb'
